name = "QuestradeAPI"
uuid = "a23c94f3-7123-4b19-879a-52247cde9a4c"
authors = ["Philippe Lacroix-Ouellette <philippe.lacroix-ouellette@hec.ca>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
